  server:
    port: 9000
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://47.98.207.48:3306/local?characterEncoding=UTF-8
  mybatis:
    mapper-locations:  classpath:mapping/*.xml
    type-aliases-package: com.lgy.login.ssologin.pojo